package cn.iocoder.educate.module.system.api.errorcode;

import cn.iocoder.educate.module.system.api.errorcode.dto.ErrorCodeAutoGenerateReqDTO;

import java.util.List;

/**
 * 错误码 Api 接口
 *
 * @Author: j-sentinel
 * @Date: 2023/8/20 11:14
 */
public interface ErrorCodeApi {

    /**
     * 自动创建错误码
     *
     * @param autoGenerateDTOs 错误码信息
     */
    void autoGenerateErrorCodeList(List<ErrorCodeAutoGenerateReqDTO> autoGenerateDTOs);

}
